indent_style = "Visual"
fn_args_density = "Compressed"
imports_layout = "Horizontal"
newline_style = "Unix"
fn_single_line = true
where_single_line = true
reorder_imports = false
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
match_arm_blocks = false
overflow_delimited_expr = true
blank_lines_upper_bound = 3
tab_spaces = 2
hard_tabs = true
edition = "2018"
max_width = 180
struct_field_align_threshold = 20
